name: kib_flutter_utils
description: "A curated collection of reusable Flutter utilities and helper widgets designed to streamline mobile app development. Ideal for developers aiming to build scalable and maintainable Flutter applications with less repetitive code."
version: 1.0.102
homepage: "https://github.com/kibmuikia/kib_flutter_utils"
issue_tracker: "https://github.com/kibmuikia/kib_flutter_utils/issues"
documentation: "https://github.com/kibmuikia/kib_flutter_utils#readme"

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  kib_debug_print: ^1.0.0
  kib_utils: ^1.0.0
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
# flutter:
# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
